/*
//normal string concallation

*/



let the firstName="samuel"
let secondName="jane"
let age=20
let address="juja county"

let usernameDetails=firstName+" "+
" he stays at " +address

//first second is 23 and be sta
console.log(usernameDetails)
console.log("User details is ",typeof userdetails)


//template string use backtricks
let userDetails2=
('${firstName} ${secodName} is ${age} years old and he stays at ${address}')
console.log(userdetails)
console.log('${first} ${secondName} is ${age}years old and he stays at at${address}')
